name: Motoblog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24818
title: Motoblog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeee6'
    - '#010101'
    - '#8e989c'
    - '#2c261f'
    - '#92725a'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
