name: Motoblog
favicon: null
layout_spectrum: 0.829077358590439
typography_spectrum: 0.17663760809227824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9705344883259386
  lightness: 0.5245372054632753
  saturation: 0.653478296007961
  rhythmicContrast: 0.26070470293052495
purpose: []
